org.gradle.jvmargs=-Xmx4g -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.caching=true
# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=true
org.gradle.vfs.watch=true
org.gradle.daemon.idletimeout=3600000
# Mod properties
common_version=1.0.0
bridge_version=1.0.0
forge_1.12.2_version=1.0.0