/*
 * SPDX-License-Identifier: MIT
 * Copyright (c) 2026 heckerpowered
 */

package heckerpowered.bridge.adapter.effect

enum class VanillaParticle(val dataCount: Int = 0) {
    ExplosionNormal,
    ExplosionLarge,
    ExplosionHuge,
    FireworksSpark,
    WaterBubble,
    WaterSplash,
    WaterWake,
    Suspended,
    SuspendedDepth,
    CriticalHit,
    MagicCriticalHit,
    SmokeNormal,
    SmokeLarge,
    Spell,
    InstantSpell,
    MobSpell,
    AmbientMobSpell,
    WitchSpell,
    DrippingWater,
    DrippingLava,
    AngryVillager,
    HappyVillager,
    TownAura,
    Note,
    Portal,
    EnchantmentTable,
    Flame,
    Lava,
    Footstep,
    Cloud,
    Redstone,
    Snowball,
    SnowShovel,
    Slime,
    Heart,
    Barrier,
    ItemCrack(2),
    BlockCrack(1),
    BlockDust(1),
    WaterDrop,
    ItemTake,
    MobAppearance,
    DragonBreath,
    EndRod,
    DamageIndicator,
    SweepAttack,
    FallingDust(1),
    Totem,
    Spit,
}
