/*
 * SPDX-License-Identifier: MIT
 * Copyright (c) 2026 heckerpowered
 */

package heckerpowered.render.engine.scene

import heckerpowered.render.engine.culling.CullingBounds

import heckerpowered.render.engine.geometry.RenderGeometry
import heckerpowered.render.engine.material.CompositingMode
import heckerpowered.render.engine.shader.program.MeshShading

/**
 * Retains a complete shader/geometry binding and its destination compositing operator.
 *
 * This is a reusable description of a visual contribution, rather than one GPU draw. Submission
 * captures placement separately, and pass preparation resolves concrete shader inputs, resources, and
 * draw arguments. Vertex-buffer geometry and geometry generated by a shader use the same path.
 *
 * [cullingBounds], when supplied, must enclose the rendered result in this element's local space,
 * including shader deformation. Absence disables bounds-based rejection; it does not request
 * bounds to be inferred from the geometry.
 */
data class GeometryElement(
    val shading: MeshShading,
    val composition: CompositingMode = CompositingMode.Replace,
    val cullingBounds: CullingBounds? = null,
) : RenderElement {
    val geometry: RenderGeometry get() = shading.geometry
}

/** Rejects unsupported element types before a geometry-specific strategy accesses their data. */
internal val RenderSubmission.geometryElement: GeometryElement
    get() = requireNotNull(element as? GeometryElement) { "This operation requires a GeometryElement, received ${element.javaClass.name}" }
